### ISSUE TITLE
issue importing nessus output

### ISSUE THREAD

**Issue by xillwillx** [lair-framework/drone-nessus#4]
having issues importing nessus output, the outport looks to be xml  
**drone-nessus 7KPogi5twvTFMka8k /tmp/SCE_6ezlue.nessus
2016/12/03 18:05:17 Fatal: Could not unmarshal JSON. Error invalid character 'B' after top-level value**

**Comment by tomsteele** [comment]
Does this help https://github.com/lair-framework/lair/wiki/Common-Issues?
